apiVersion: batch/v1
kind: Job
metadata:
  name: sniffer-example-hong
  generateName: sniffer-example-hong-
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - image: ghcr.io/mmazurekgda/data-baits:main
        tty: true
        imagePullPolicy: Always
        name: sniffer
        command:
        - python
        - -m
        - data_baits
        - --verbosity
        - DEBUG
        - deploy
        - --in_cluster
        - --from_secret
      volumes:
      - name: volume-kf-pipeline-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
              audience: pipelines.kubeflow.org
