"""create_entities

Revision ID: f989cde7e385
Revises:
Create Date: 2024-01-20 22:27:14.562195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f989cde7e385"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_test_mysql() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_with_float_on_my_sqls",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade_test_mysql() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity_with_float_on_my_sqls")
    # ### end Alembic commands ###


def upgrade_test_sqlite() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity_with_float_on_sqlites",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade_test_sqlite() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entity_with_float_on_sqlites")
    # ### end Alembic commands ###
